/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminUpdateUserNameDTO
 */
export interface AdminUpdateUserNameDTO {
  /**
   *
   * @type {string}
   * @memberof AdminUpdateUserNameDTO
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof AdminUpdateUserNameDTO
   */
  name?: string | null;
}

/**
 * Check if a given object implements the AdminUpdateUserNameDTO interface.
 */
export function instanceOfAdminUpdateUserNameDTO(value: object): value is AdminUpdateUserNameDTO {
  return true;
}

export function AdminUpdateUserNameDTOFromJSON(json: any): AdminUpdateUserNameDTO {
  return AdminUpdateUserNameDTOFromJSONTyped(json, false);
}

export function AdminUpdateUserNameDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUpdateUserNameDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function AdminUpdateUserNameDTOToJSON(json: any): AdminUpdateUserNameDTO {
  return AdminUpdateUserNameDTOToJSONTyped(json, false);
}

export function AdminUpdateUserNameDTOToJSONTyped(value?: AdminUpdateUserNameDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
  };
}
