/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApplyEmailActionResponse
 */
export interface ApplyEmailActionResponse {
  /**
   *
   * @type {boolean}
   * @memberof ApplyEmailActionResponse
   */
  appliedSuccessfully?: boolean;
}

/**
 * Check if a given object implements the ApplyEmailActionResponse interface.
 */
export function instanceOfApplyEmailActionResponse(value: object): value is ApplyEmailActionResponse {
  return true;
}

export function ApplyEmailActionResponseFromJSON(json: any): ApplyEmailActionResponse {
  return ApplyEmailActionResponseFromJSONTyped(json, false);
}

export function ApplyEmailActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyEmailActionResponse {
  if (json == null) {
    return json;
  }
  return {
    appliedSuccessfully: json["appliedSuccessfully"] == null ? undefined : json["appliedSuccessfully"],
  };
}

export function ApplyEmailActionResponseToJSON(json: any): ApplyEmailActionResponse {
  return ApplyEmailActionResponseToJSONTyped(json, false);
}

export function ApplyEmailActionResponseToJSONTyped(value?: ApplyEmailActionResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    appliedSuccessfully: value["appliedSuccessfully"],
  };
}
