/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { ApplyEmailActionResponse } from "./ApplyEmailActionResponse";
import {
  ApplyEmailActionResponseFromJSON,
  ApplyEmailActionResponseFromJSONTyped,
  ApplyEmailActionResponseToJSON,
  ApplyEmailActionResponseToJSONTyped,
} from "./ApplyEmailActionResponse";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface ApplyEmailActionResponseResponseWrapper
 */
export interface ApplyEmailActionResponseResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof ApplyEmailActionResponseResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof ApplyEmailActionResponseResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {ApplyEmailActionResponse}
   * @memberof ApplyEmailActionResponseResponseWrapper
   */
  response?: ApplyEmailActionResponse;
}

/**
 * Check if a given object implements the ApplyEmailActionResponseResponseWrapper interface.
 */
export function instanceOfApplyEmailActionResponseResponseWrapper(value: object): value is ApplyEmailActionResponseResponseWrapper {
  return true;
}

export function ApplyEmailActionResponseResponseWrapperFromJSON(json: any): ApplyEmailActionResponseResponseWrapper {
  return ApplyEmailActionResponseResponseWrapperFromJSONTyped(json, false);
}

export function ApplyEmailActionResponseResponseWrapperFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApplyEmailActionResponseResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : ApplyEmailActionResponseFromJSON(json["response"]),
  };
}

export function ApplyEmailActionResponseResponseWrapperToJSON(json: any): ApplyEmailActionResponseResponseWrapper {
  return ApplyEmailActionResponseResponseWrapperToJSONTyped(json, false);
}

export function ApplyEmailActionResponseResponseWrapperToJSONTyped(
  value?: ApplyEmailActionResponseResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: ApplyEmailActionResponseToJSON(value["response"]),
  };
}
