/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreatePermissionDTO
 */
export interface CreatePermissionDTO {
  /**
   *
   * @type {string}
   * @memberof CreatePermissionDTO
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreatePermissionDTO
   */
  key?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreatePermissionDTO
   */
  serviceId?: string | null;
}

/**
 * Check if a given object implements the CreatePermissionDTO interface.
 */
export function instanceOfCreatePermissionDTO(value: object): value is CreatePermissionDTO {
  return true;
}

export function CreatePermissionDTOFromJSON(json: any): CreatePermissionDTO {
  return CreatePermissionDTOFromJSONTyped(json, false);
}

export function CreatePermissionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePermissionDTO {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    key: json["key"] == null ? undefined : json["key"],
    serviceId: json["serviceId"] == null ? undefined : json["serviceId"],
  };
}

export function CreatePermissionDTOToJSON(json: any): CreatePermissionDTO {
  return CreatePermissionDTOToJSONTyped(json, false);
}

export function CreatePermissionDTOToJSONTyped(value?: CreatePermissionDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    key: value["key"],
    serviceId: value["serviceId"],
  };
}
