/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EmailTemplateType } from "./EmailTemplateType";
import {
  EmailTemplateTypeFromJSON,
  EmailTemplateTypeFromJSONTyped,
  EmailTemplateTypeToJSON,
  EmailTemplateTypeToJSONTyped,
} from "./EmailTemplateType";

/**
 *
 * @export
 * @interface CreateEmailTemplateDTO
 */
export interface CreateEmailTemplateDTO {
  /**
   *
   * @type {string}
   * @memberof CreateEmailTemplateDTO
   */
  name?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof CreateEmailTemplateDTO
   */
  isActive?: boolean;
  /**
   *
   * @type {EmailTemplateType}
   * @memberof CreateEmailTemplateDTO
   */
  type?: EmailTemplateType;
  /**
   *
   * @type {string}
   * @memberof CreateEmailTemplateDTO
   */
  subject?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateEmailTemplateDTO
   */
  body?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateEmailTemplateDTO
   */
  htmlBody?: string | null;
}

/**
 * Check if a given object implements the CreateEmailTemplateDTO interface.
 */
export function instanceOfCreateEmailTemplateDTO(value: object): value is CreateEmailTemplateDTO {
  return true;
}

export function CreateEmailTemplateDTOFromJSON(json: any): CreateEmailTemplateDTO {
  return CreateEmailTemplateDTOFromJSONTyped(json, false);
}

export function CreateEmailTemplateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmailTemplateDTO {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    isActive: json["isActive"] == null ? undefined : json["isActive"],
    type: json["type"] == null ? undefined : EmailTemplateTypeFromJSON(json["type"]),
    subject: json["subject"] == null ? undefined : json["subject"],
    body: json["body"] == null ? undefined : json["body"],
    htmlBody: json["htmlBody"] == null ? undefined : json["htmlBody"],
  };
}

export function CreateEmailTemplateDTOToJSON(json: any): CreateEmailTemplateDTO {
  return CreateEmailTemplateDTOToJSONTyped(json, false);
}

export function CreateEmailTemplateDTOToJSONTyped(value?: CreateEmailTemplateDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    isActive: value["isActive"],
    type: EmailTemplateTypeToJSON(value["type"]),
    subject: value["subject"],
    body: value["body"],
    htmlBody: value["htmlBody"],
  };
}
