/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateServiceDTO
 */
export interface CreateServiceDTO {
  /**
   *
   * @type {string}
   * @memberof CreateServiceDTO
   */
  name?: string | null;
}

/**
 * Check if a given object implements the CreateServiceDTO interface.
 */
export function instanceOfCreateServiceDTO(value: object): value is CreateServiceDTO {
  return true;
}

export function CreateServiceDTOFromJSON(json: any): CreateServiceDTO {
  return CreateServiceDTOFromJSONTyped(json, false);
}

export function CreateServiceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServiceDTO {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function CreateServiceDTOToJSON(json: any): CreateServiceDTO {
  return CreateServiceDTOToJSONTyped(json, false);
}

export function CreateServiceDTOToJSONTyped(value?: CreateServiceDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
  };
}
