/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateUserDTO
 */
export interface CreateUserDTO {
  /**
   *
   * @type {string}
   * @memberof CreateUserDTO
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserDTO
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserDTO
   */
  name?: string | null;
}

/**
 * Check if a given object implements the CreateUserDTO interface.
 */
export function instanceOfCreateUserDTO(value: object): value is CreateUserDTO {
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  return true;
}

export function CreateUserDTOFromJSON(json: any): CreateUserDTO {
  return CreateUserDTOFromJSONTyped(json, false);
}

export function CreateUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDTO {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function CreateUserDTOToJSON(json: any): CreateUserDTO {
  return CreateUserDTOToJSONTyped(json, false);
}

export function CreateUserDTOToJSONTyped(value?: CreateUserDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    password: value["password"],
    name: value["name"],
  };
}
