/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { DecodedEmailActionDTO } from "./DecodedEmailActionDTO";
import {
  DecodedEmailActionDTOFromJSON,
  DecodedEmailActionDTOFromJSONTyped,
  DecodedEmailActionDTOToJSON,
  DecodedEmailActionDTOToJSONTyped,
} from "./DecodedEmailActionDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface DecodedEmailActionDTOResponseWrapper
 */
export interface DecodedEmailActionDTOResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof DecodedEmailActionDTOResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof DecodedEmailActionDTOResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {DecodedEmailActionDTO}
   * @memberof DecodedEmailActionDTOResponseWrapper
   */
  response?: DecodedEmailActionDTO;
}

/**
 * Check if a given object implements the DecodedEmailActionDTOResponseWrapper interface.
 */
export function instanceOfDecodedEmailActionDTOResponseWrapper(value: object): value is DecodedEmailActionDTOResponseWrapper {
  return true;
}

export function DecodedEmailActionDTOResponseWrapperFromJSON(json: any): DecodedEmailActionDTOResponseWrapper {
  return DecodedEmailActionDTOResponseWrapperFromJSONTyped(json, false);
}

export function DecodedEmailActionDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodedEmailActionDTOResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : DecodedEmailActionDTOFromJSON(json["response"]),
  };
}

export function DecodedEmailActionDTOResponseWrapperToJSON(json: any): DecodedEmailActionDTOResponseWrapper {
  return DecodedEmailActionDTOResponseWrapperToJSONTyped(json, false);
}

export function DecodedEmailActionDTOResponseWrapperToJSONTyped(
  value?: DecodedEmailActionDTOResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: DecodedEmailActionDTOToJSON(value["response"]),
  };
}
