/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserBasicDTO } from "./UserBasicDTO";
import { UserBasicDTOFromJSON, UserBasicDTOFromJSONTyped, UserBasicDTOToJSON, UserBasicDTOToJSONTyped } from "./UserBasicDTO";
import type { EmailActionType } from "./EmailActionType";
import { EmailActionTypeFromJSON, EmailActionTypeFromJSONTyped, EmailActionTypeToJSON, EmailActionTypeToJSONTyped } from "./EmailActionType";

/**
 *
 * @export
 * @interface DecodedEmailActionDTO
 */
export interface DecodedEmailActionDTO {
  /**
   *
   * @type {string}
   * @memberof DecodedEmailActionDTO
   */
  id?: string | null;
  /**
   *
   * @type {UserBasicDTO}
   * @memberof DecodedEmailActionDTO
   */
  user?: UserBasicDTO;
  /**
   *
   * @type {string}
   * @memberof DecodedEmailActionDTO
   */
  data?: string | null;
  /**
   *
   * @type {EmailActionType}
   * @memberof DecodedEmailActionDTO
   */
  type?: EmailActionType;
  /**
   *
   * @type {Date}
   * @memberof DecodedEmailActionDTO
   */
  expiresAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof DecodedEmailActionDTO
   */
  createdAt?: Date;
}

/**
 * Check if a given object implements the DecodedEmailActionDTO interface.
 */
export function instanceOfDecodedEmailActionDTO(value: object): value is DecodedEmailActionDTO {
  return true;
}

export function DecodedEmailActionDTOFromJSON(json: any): DecodedEmailActionDTO {
  return DecodedEmailActionDTOFromJSONTyped(json, false);
}

export function DecodedEmailActionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodedEmailActionDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    user: json["user"] == null ? undefined : UserBasicDTOFromJSON(json["user"]),
    data: json["data"] == null ? undefined : json["data"],
    type: json["type"] == null ? undefined : EmailActionTypeFromJSON(json["type"]),
    expiresAt: json["expiresAt"] == null ? undefined : new Date(json["expiresAt"]),
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
  };
}

export function DecodedEmailActionDTOToJSON(json: any): DecodedEmailActionDTO {
  return DecodedEmailActionDTOToJSONTyped(json, false);
}

export function DecodedEmailActionDTOToJSONTyped(value?: DecodedEmailActionDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    user: UserBasicDTOToJSON(value["user"]),
    data: value["data"],
    type: EmailActionTypeToJSON(value["type"]),
    expiresAt: value["expiresAt"] == null ? undefined : value["expiresAt"].toISOString(),
    createdAt: value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
  };
}
