/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EmailActionDTO } from "./EmailActionDTO";
import { EmailActionDTOFromJSON, EmailActionDTOFromJSONTyped, EmailActionDTOToJSON, EmailActionDTOToJSONTyped } from "./EmailActionDTO";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface EmailActionDTOListResponseWrapper
 */
export interface EmailActionDTOListResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof EmailActionDTOListResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof EmailActionDTOListResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {Array<EmailActionDTO>}
   * @memberof EmailActionDTOListResponseWrapper
   */
  response?: Array<EmailActionDTO> | null;
}

/**
 * Check if a given object implements the EmailActionDTOListResponseWrapper interface.
 */
export function instanceOfEmailActionDTOListResponseWrapper(value: object): value is EmailActionDTOListResponseWrapper {
  return true;
}

export function EmailActionDTOListResponseWrapperFromJSON(json: any): EmailActionDTOListResponseWrapper {
  return EmailActionDTOListResponseWrapperFromJSONTyped(json, false);
}

export function EmailActionDTOListResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailActionDTOListResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : (json["response"] as Array<any>).map(EmailActionDTOFromJSON),
  };
}

export function EmailActionDTOListResponseWrapperToJSON(json: any): EmailActionDTOListResponseWrapper {
  return EmailActionDTOListResponseWrapperToJSONTyped(json, false);
}

export function EmailActionDTOListResponseWrapperToJSONTyped(
  value?: EmailActionDTOListResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: value["response"] == null ? undefined : (value["response"] as Array<any>).map(EmailActionDTOToJSON),
  };
}
