/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EmailTemplateDTO } from "./EmailTemplateDTO";
import { EmailTemplateDTOFromJSON, EmailTemplateDTOFromJSONTyped, EmailTemplateDTOToJSON, EmailTemplateDTOToJSONTyped } from "./EmailTemplateDTO";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface EmailTemplateDTOListResponseWrapper
 */
export interface EmailTemplateDTOListResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof EmailTemplateDTOListResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof EmailTemplateDTOListResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {Array<EmailTemplateDTO>}
   * @memberof EmailTemplateDTOListResponseWrapper
   */
  response?: Array<EmailTemplateDTO> | null;
}

/**
 * Check if a given object implements the EmailTemplateDTOListResponseWrapper interface.
 */
export function instanceOfEmailTemplateDTOListResponseWrapper(value: object): value is EmailTemplateDTOListResponseWrapper {
  return true;
}

export function EmailTemplateDTOListResponseWrapperFromJSON(json: any): EmailTemplateDTOListResponseWrapper {
  return EmailTemplateDTOListResponseWrapperFromJSONTyped(json, false);
}

export function EmailTemplateDTOListResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplateDTOListResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : (json["response"] as Array<any>).map(EmailTemplateDTOFromJSON),
  };
}

export function EmailTemplateDTOListResponseWrapperToJSON(json: any): EmailTemplateDTOListResponseWrapper {
  return EmailTemplateDTOListResponseWrapperToJSONTyped(json, false);
}

export function EmailTemplateDTOListResponseWrapperToJSONTyped(
  value?: EmailTemplateDTOListResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: value["response"] == null ? undefined : (value["response"] as Array<any>).map(EmailTemplateDTOToJSON),
  };
}
