/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const EmailActionType = {
  VerifyEmail: "VerifyEmail",
  PasswordReset: "PasswordReset",
  EmailCode: "EmailCode",
  EmailSignIn: "EmailSignIn",
  DeleteAccount: "DeleteAccount",
  ChangeEmail: "ChangeEmail",
} as const;
export type EmailActionType = (typeof EmailActionType)[keyof typeof EmailActionType];

export function instanceOfEmailActionType(value: any): boolean {
  for (const key in EmailActionType) {
    if (Object.prototype.hasOwnProperty.call(EmailActionType, key)) {
      if (EmailActionType[key as keyof typeof EmailActionType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function EmailActionTypeFromJSON(json: any): EmailActionType {
  return EmailActionTypeFromJSONTyped(json, false);
}

export function EmailActionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailActionType {
  return json as EmailActionType;
}

export function EmailActionTypeToJSON(value?: EmailActionType | null): any {
  return value as any;
}

export function EmailActionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): EmailActionType {
  return value as EmailActionType;
}
