/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EmailTemplateDTO } from "./EmailTemplateDTO";
import { EmailTemplateDTOFromJSON, EmailTemplateDTOFromJSONTyped, EmailTemplateDTOToJSON, EmailTemplateDTOToJSONTyped } from "./EmailTemplateDTO";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface EmailTemplateDTOResponseWrapper
 */
export interface EmailTemplateDTOResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof EmailTemplateDTOResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof EmailTemplateDTOResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {EmailTemplateDTO}
   * @memberof EmailTemplateDTOResponseWrapper
   */
  response?: EmailTemplateDTO;
}

/**
 * Check if a given object implements the EmailTemplateDTOResponseWrapper interface.
 */
export function instanceOfEmailTemplateDTOResponseWrapper(value: object): value is EmailTemplateDTOResponseWrapper {
  return true;
}

export function EmailTemplateDTOResponseWrapperFromJSON(json: any): EmailTemplateDTOResponseWrapper {
  return EmailTemplateDTOResponseWrapperFromJSONTyped(json, false);
}

export function EmailTemplateDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplateDTOResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : EmailTemplateDTOFromJSON(json["response"]),
  };
}

export function EmailTemplateDTOResponseWrapperToJSON(json: any): EmailTemplateDTOResponseWrapper {
  return EmailTemplateDTOResponseWrapperToJSONTyped(json, false);
}

export function EmailTemplateDTOResponseWrapperToJSONTyped(
  value?: EmailTemplateDTOResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: EmailTemplateDTOToJSON(value["response"]),
  };
}
