/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { FullSessionDTO } from "./FullSessionDTO";
import { FullSessionDTOFromJSON, FullSessionDTOFromJSONTyped, FullSessionDTOToJSON, FullSessionDTOToJSONTyped } from "./FullSessionDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface FullSessionDTOResponseWrapper
 */
export interface FullSessionDTOResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof FullSessionDTOResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof FullSessionDTOResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {FullSessionDTO}
   * @memberof FullSessionDTOResponseWrapper
   */
  response?: FullSessionDTO;
}

/**
 * Check if a given object implements the FullSessionDTOResponseWrapper interface.
 */
export function instanceOfFullSessionDTOResponseWrapper(value: object): value is FullSessionDTOResponseWrapper {
  return true;
}

export function FullSessionDTOResponseWrapperFromJSON(json: any): FullSessionDTOResponseWrapper {
  return FullSessionDTOResponseWrapperFromJSONTyped(json, false);
}

export function FullSessionDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullSessionDTOResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : FullSessionDTOFromJSON(json["response"]),
  };
}

export function FullSessionDTOResponseWrapperToJSON(json: any): FullSessionDTOResponseWrapper {
  return FullSessionDTOResponseWrapperToJSONTyped(json, false);
}

export function FullSessionDTOResponseWrapperToJSONTyped(value?: FullSessionDTOResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: FullSessionDTOToJSON(value["response"]),
  };
}
