/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserDTO } from "./UserDTO";
import { UserDTOFromJSON, UserDTOFromJSONTyped, UserDTOToJSON, UserDTOToJSONTyped } from "./UserDTO";
import type { ServiceDTO } from "./ServiceDTO";
import { ServiceDTOFromJSON, ServiceDTOFromJSONTyped, ServiceDTOToJSON, ServiceDTOToJSONTyped } from "./ServiceDTO";

/**
 *
 * @export
 * @interface FullSessionDTO
 */
export interface FullSessionDTO {
  /**
   *
   * @type {string}
   * @memberof FullSessionDTO
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof FullSessionDTO
   */
  userId?: string | null;
  /**
   *
   * @type {string}
   * @memberof FullSessionDTO
   */
  serviceId?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof FullSessionDTO
   */
  is2FAConfirmed?: boolean;
  /**
   *
   * @type {Date}
   * @memberof FullSessionDTO
   */
  expiresAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof FullSessionDTO
   */
  createdAt?: Date;
  /**
   *
   * @type {string}
   * @memberof FullSessionDTO
   */
  ipAddress?: string | null;
  /**
   *
   * @type {string}
   * @memberof FullSessionDTO
   */
  device?: string | null;
  /**
   *
   * @type {string}
   * @memberof FullSessionDTO
   */
  browser?: string | null;
  /**
   *
   * @type {string}
   * @memberof FullSessionDTO
   */
  os?: string | null;
  /**
   *
   * @type {ServiceDTO}
   * @memberof FullSessionDTO
   */
  service?: ServiceDTO;
  /**
   *
   * @type {UserDTO}
   * @memberof FullSessionDTO
   */
  user?: UserDTO;
}

/**
 * Check if a given object implements the FullSessionDTO interface.
 */
export function instanceOfFullSessionDTO(value: object): value is FullSessionDTO {
  return true;
}

export function FullSessionDTOFromJSON(json: any): FullSessionDTO {
  return FullSessionDTOFromJSONTyped(json, false);
}

export function FullSessionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullSessionDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    userId: json["userId"] == null ? undefined : json["userId"],
    serviceId: json["serviceId"] == null ? undefined : json["serviceId"],
    is2FAConfirmed: json["is2FAConfirmed"] == null ? undefined : json["is2FAConfirmed"],
    expiresAt: json["expiresAt"] == null ? undefined : new Date(json["expiresAt"]),
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    ipAddress: json["ipAddress"] == null ? undefined : json["ipAddress"],
    device: json["device"] == null ? undefined : json["device"],
    browser: json["browser"] == null ? undefined : json["browser"],
    os: json["os"] == null ? undefined : json["os"],
    service: json["service"] == null ? undefined : ServiceDTOFromJSON(json["service"]),
    user: json["user"] == null ? undefined : UserDTOFromJSON(json["user"]),
  };
}

export function FullSessionDTOToJSON(json: any): FullSessionDTO {
  return FullSessionDTOToJSONTyped(json, false);
}

export function FullSessionDTOToJSONTyped(value?: FullSessionDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    serviceId: value["serviceId"],
    is2FAConfirmed: value["is2FAConfirmed"],
    expiresAt: value["expiresAt"] == null ? undefined : value["expiresAt"].toISOString(),
    createdAt: value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
    ipAddress: value["ipAddress"],
    device: value["device"],
    browser: value["browser"],
    os: value["os"],
    service: ServiceDTOToJSON(value["service"]),
    user: UserDTOToJSON(value["user"]),
  };
}
