/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Model2FAEntrySetupDTO
 */
export interface Model2FAEntrySetupDTO {
  /**
   *
   * @type {string}
   * @memberof Model2FAEntrySetupDTO
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof Model2FAEntrySetupDTO
   */
  _2fASecret?: string | null;
  /**
   *
   * @type {string}
   * @memberof Model2FAEntrySetupDTO
   */
  recoveryCode?: string | null;
  /**
   *
   * @type {string}
   * @memberof Model2FAEntrySetupDTO
   */
  qrCodeUrl?: string | null;
}

/**
 * Check if a given object implements the Model2FAEntrySetupDTO interface.
 */
export function instanceOfModel2FAEntrySetupDTO(value: object): value is Model2FAEntrySetupDTO {
  return true;
}

export function Model2FAEntrySetupDTOFromJSON(json: any): Model2FAEntrySetupDTO {
  return Model2FAEntrySetupDTOFromJSONTyped(json, false);
}

export function Model2FAEntrySetupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model2FAEntrySetupDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    _2fASecret: json["_2FASecret"] == null ? undefined : json["_2FASecret"],
    recoveryCode: json["recoveryCode"] == null ? undefined : json["recoveryCode"],
    qrCodeUrl: json["qrCodeUrl"] == null ? undefined : json["qrCodeUrl"],
  };
}

export function Model2FAEntrySetupDTOToJSON(json: any): Model2FAEntrySetupDTO {
  return Model2FAEntrySetupDTOToJSONTyped(json, false);
}

export function Model2FAEntrySetupDTOToJSONTyped(value?: Model2FAEntrySetupDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    _2FASecret: value["_2fASecret"],
    recoveryCode: value["recoveryCode"],
    qrCodeUrl: value["qrCodeUrl"],
  };
}
