/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { Model2FAEntrySetupDTO } from "./Model2FAEntrySetupDTO";
import {
  Model2FAEntrySetupDTOFromJSON,
  Model2FAEntrySetupDTOFromJSONTyped,
  Model2FAEntrySetupDTOToJSON,
  Model2FAEntrySetupDTOToJSONTyped,
} from "./Model2FAEntrySetupDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface Model2FAEntrySetupDTOResponseWrapper
 */
export interface Model2FAEntrySetupDTOResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof Model2FAEntrySetupDTOResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof Model2FAEntrySetupDTOResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {Model2FAEntrySetupDTO}
   * @memberof Model2FAEntrySetupDTOResponseWrapper
   */
  response?: Model2FAEntrySetupDTO;
}

/**
 * Check if a given object implements the Model2FAEntrySetupDTOResponseWrapper interface.
 */
export function instanceOfModel2FAEntrySetupDTOResponseWrapper(value: object): value is Model2FAEntrySetupDTOResponseWrapper {
  return true;
}

export function Model2FAEntrySetupDTOResponseWrapperFromJSON(json: any): Model2FAEntrySetupDTOResponseWrapper {
  return Model2FAEntrySetupDTOResponseWrapperFromJSONTyped(json, false);
}

export function Model2FAEntrySetupDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model2FAEntrySetupDTOResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : Model2FAEntrySetupDTOFromJSON(json["response"]),
  };
}

export function Model2FAEntrySetupDTOResponseWrapperToJSON(json: any): Model2FAEntrySetupDTOResponseWrapper {
  return Model2FAEntrySetupDTOResponseWrapperToJSONTyped(json, false);
}

export function Model2FAEntrySetupDTOResponseWrapperToJSONTyped(
  value?: Model2FAEntrySetupDTOResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: Model2FAEntrySetupDTOToJSON(value["response"]),
  };
}
