/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Model2FAEntryDTO
 */
export interface Model2FAEntryDTO {
  /**
   *
   * @type {string}
   * @memberof Model2FAEntryDTO
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof Model2FAEntryDTO
   */
  name?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof Model2FAEntryDTO
   */
  isActive?: boolean;
  /**
   *
   * @type {Date}
   * @memberof Model2FAEntryDTO
   */
  createdAt?: Date;
}

/**
 * Check if a given object implements the Model2FAEntryDTO interface.
 */
export function instanceOfModel2FAEntryDTO(value: object): value is Model2FAEntryDTO {
  return true;
}

export function Model2FAEntryDTOFromJSON(json: any): Model2FAEntryDTO {
  return Model2FAEntryDTOFromJSONTyped(json, false);
}

export function Model2FAEntryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model2FAEntryDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    isActive: json["isActive"] == null ? undefined : json["isActive"],
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
  };
}

export function Model2FAEntryDTOToJSON(json: any): Model2FAEntryDTO {
  return Model2FAEntryDTOToJSONTyped(json, false);
}

export function Model2FAEntryDTOToJSONTyped(value?: Model2FAEntryDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    isActive: value["isActive"],
    createdAt: value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
  };
}
