/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";
import type { NeutralizeEmailActionResponse } from "./NeutralizeEmailActionResponse";
import {
  NeutralizeEmailActionResponseFromJSON,
  NeutralizeEmailActionResponseFromJSONTyped,
  NeutralizeEmailActionResponseToJSON,
  NeutralizeEmailActionResponseToJSONTyped,
} from "./NeutralizeEmailActionResponse";

/**
 *
 * @export
 * @interface NeutralizeEmailActionResponseResponseWrapper
 */
export interface NeutralizeEmailActionResponseResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof NeutralizeEmailActionResponseResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof NeutralizeEmailActionResponseResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {NeutralizeEmailActionResponse}
   * @memberof NeutralizeEmailActionResponseResponseWrapper
   */
  response?: NeutralizeEmailActionResponse;
}

/**
 * Check if a given object implements the NeutralizeEmailActionResponseResponseWrapper interface.
 */
export function instanceOfNeutralizeEmailActionResponseResponseWrapper(value: object): value is NeutralizeEmailActionResponseResponseWrapper {
  return true;
}

export function NeutralizeEmailActionResponseResponseWrapperFromJSON(json: any): NeutralizeEmailActionResponseResponseWrapper {
  return NeutralizeEmailActionResponseResponseWrapperFromJSONTyped(json, false);
}

export function NeutralizeEmailActionResponseResponseWrapperFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NeutralizeEmailActionResponseResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : NeutralizeEmailActionResponseFromJSON(json["response"]),
  };
}

export function NeutralizeEmailActionResponseResponseWrapperToJSON(json: any): NeutralizeEmailActionResponseResponseWrapper {
  return NeutralizeEmailActionResponseResponseWrapperToJSONTyped(json, false);
}

export function NeutralizeEmailActionResponseResponseWrapperToJSONTyped(
  value?: NeutralizeEmailActionResponseResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: NeutralizeEmailActionResponseToJSON(value["response"]),
  };
}
