/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NeutralizeEmailActionResponse
 */
export interface NeutralizeEmailActionResponse {
  /**
   *
   * @type {boolean}
   * @memberof NeutralizeEmailActionResponse
   */
  neutralizedSuccessfully?: boolean;
}

/**
 * Check if a given object implements the NeutralizeEmailActionResponse interface.
 */
export function instanceOfNeutralizeEmailActionResponse(value: object): value is NeutralizeEmailActionResponse {
  return true;
}

export function NeutralizeEmailActionResponseFromJSON(json: any): NeutralizeEmailActionResponse {
  return NeutralizeEmailActionResponseFromJSONTyped(json, false);
}

export function NeutralizeEmailActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NeutralizeEmailActionResponse {
  if (json == null) {
    return json;
  }
  return {
    neutralizedSuccessfully: json["neutralizedSuccessfully"] == null ? undefined : json["neutralizedSuccessfully"],
  };
}

export function NeutralizeEmailActionResponseToJSON(json: any): NeutralizeEmailActionResponse {
  return NeutralizeEmailActionResponseToJSONTyped(json, false);
}

export function NeutralizeEmailActionResponseToJSONTyped(value?: NeutralizeEmailActionResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    neutralizedSuccessfully: value["neutralizedSuccessfully"],
  };
}
