/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { PermissionDTO } from "./PermissionDTO";
import { PermissionDTOFromJSON, PermissionDTOFromJSONTyped, PermissionDTOToJSON, PermissionDTOToJSONTyped } from "./PermissionDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface PermissionDTOListResponseWrapper
 */
export interface PermissionDTOListResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof PermissionDTOListResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof PermissionDTOListResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {Array<PermissionDTO>}
   * @memberof PermissionDTOListResponseWrapper
   */
  response?: Array<PermissionDTO> | null;
}

/**
 * Check if a given object implements the PermissionDTOListResponseWrapper interface.
 */
export function instanceOfPermissionDTOListResponseWrapper(value: object): value is PermissionDTOListResponseWrapper {
  return true;
}

export function PermissionDTOListResponseWrapperFromJSON(json: any): PermissionDTOListResponseWrapper {
  return PermissionDTOListResponseWrapperFromJSONTyped(json, false);
}

export function PermissionDTOListResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDTOListResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : (json["response"] as Array<any>).map(PermissionDTOFromJSON),
  };
}

export function PermissionDTOListResponseWrapperToJSON(json: any): PermissionDTOListResponseWrapper {
  return PermissionDTOListResponseWrapperToJSONTyped(json, false);
}

export function PermissionDTOListResponseWrapperToJSONTyped(
  value?: PermissionDTOListResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: value["response"] == null ? undefined : (value["response"] as Array<any>).map(PermissionDTOToJSON),
  };
}
