/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ServiceBasicDTO } from "./ServiceBasicDTO";
import { ServiceBasicDTOFromJSON, ServiceBasicDTOFromJSONTyped, ServiceBasicDTOToJSON, ServiceBasicDTOToJSONTyped } from "./ServiceBasicDTO";

/**
 *
 * @export
 * @interface PermissionDTO
 */
export interface PermissionDTO {
  /**
   *
   * @type {string}
   * @memberof PermissionDTO
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof PermissionDTO
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof PermissionDTO
   */
  key?: string | null;
  /**
   *
   * @type {string}
   * @memberof PermissionDTO
   */
  serviceId?: string | null;
  /**
   *
   * @type {Date}
   * @memberof PermissionDTO
   */
  createdAt?: Date;
  /**
   *
   * @type {ServiceBasicDTO}
   * @memberof PermissionDTO
   */
  service?: ServiceBasicDTO;
}

/**
 * Check if a given object implements the PermissionDTO interface.
 */
export function instanceOfPermissionDTO(value: object): value is PermissionDTO {
  return true;
}

export function PermissionDTOFromJSON(json: any): PermissionDTO {
  return PermissionDTOFromJSONTyped(json, false);
}

export function PermissionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    key: json["key"] == null ? undefined : json["key"],
    serviceId: json["serviceId"] == null ? undefined : json["serviceId"],
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    service: json["service"] == null ? undefined : ServiceBasicDTOFromJSON(json["service"]),
  };
}

export function PermissionDTOToJSON(json: any): PermissionDTO {
  return PermissionDTOToJSONTyped(json, false);
}

export function PermissionDTOToJSONTyped(value?: PermissionDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    key: value["key"],
    serviceId: value["serviceId"],
    createdAt: value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
    service: ServiceBasicDTOToJSON(value["service"]),
  };
}
