/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RequestEmailActionResponse
 */
export interface RequestEmailActionResponse {
  /**
   *
   * @type {boolean}
   * @memberof RequestEmailActionResponse
   */
  sentSuccessfully?: boolean;
  /**
   *
   * @type {number}
   * @memberof RequestEmailActionResponse
   */
  secondsToWait?: number | null;
}

/**
 * Check if a given object implements the RequestEmailActionResponse interface.
 */
export function instanceOfRequestEmailActionResponse(value: object): value is RequestEmailActionResponse {
  return true;
}

export function RequestEmailActionResponseFromJSON(json: any): RequestEmailActionResponse {
  return RequestEmailActionResponseFromJSONTyped(json, false);
}

export function RequestEmailActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestEmailActionResponse {
  if (json == null) {
    return json;
  }
  return {
    sentSuccessfully: json["sentSuccessfully"] == null ? undefined : json["sentSuccessfully"],
    secondsToWait: json["secondsToWait"] == null ? undefined : json["secondsToWait"],
  };
}

export function RequestEmailActionResponseToJSON(json: any): RequestEmailActionResponse {
  return RequestEmailActionResponseToJSONTyped(json, false);
}

export function RequestEmailActionResponseToJSONTyped(value?: RequestEmailActionResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    sentSuccessfully: value["sentSuccessfully"],
    secondsToWait: value["secondsToWait"],
  };
}
