/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RequestAction = {
  Add: "Add",
  Remove: "Remove",
} as const;
export type RequestAction = (typeof RequestAction)[keyof typeof RequestAction];

export function instanceOfRequestAction(value: any): boolean {
  for (const key in RequestAction) {
    if (Object.prototype.hasOwnProperty.call(RequestAction, key)) {
      if (RequestAction[key as keyof typeof RequestAction] === value) {
        return true;
      }
    }
  }
  return false;
}

export function RequestActionFromJSON(json: any): RequestAction {
  return RequestActionFromJSONTyped(json, false);
}

export function RequestActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestAction {
  return json as RequestAction;
}

export function RequestActionToJSON(value?: RequestAction | null): any {
  return value as any;
}

export function RequestActionToJSONTyped(value: any, ignoreDiscriminator: boolean): RequestAction {
  return value as RequestAction;
}
