/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";
import type { RequestEmailActionResponse } from "./RequestEmailActionResponse";
import {
  RequestEmailActionResponseFromJSON,
  RequestEmailActionResponseFromJSONTyped,
  RequestEmailActionResponseToJSON,
  RequestEmailActionResponseToJSONTyped,
} from "./RequestEmailActionResponse";

/**
 *
 * @export
 * @interface RequestEmailActionResponseResponseWrapper
 */
export interface RequestEmailActionResponseResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof RequestEmailActionResponseResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof RequestEmailActionResponseResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {RequestEmailActionResponse}
   * @memberof RequestEmailActionResponseResponseWrapper
   */
  response?: RequestEmailActionResponse;
}

/**
 * Check if a given object implements the RequestEmailActionResponseResponseWrapper interface.
 */
export function instanceOfRequestEmailActionResponseResponseWrapper(value: object): value is RequestEmailActionResponseResponseWrapper {
  return true;
}

export function RequestEmailActionResponseResponseWrapperFromJSON(json: any): RequestEmailActionResponseResponseWrapper {
  return RequestEmailActionResponseResponseWrapperFromJSONTyped(json, false);
}

export function RequestEmailActionResponseResponseWrapperFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RequestEmailActionResponseResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : RequestEmailActionResponseFromJSON(json["response"]),
  };
}

export function RequestEmailActionResponseResponseWrapperToJSON(json: any): RequestEmailActionResponseResponseWrapper {
  return RequestEmailActionResponseResponseWrapperToJSONTyped(json, false);
}

export function RequestEmailActionResponseResponseWrapperToJSONTyped(
  value?: RequestEmailActionResponseResponseWrapper | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: RequestEmailActionResponseToJSON(value["response"]),
  };
}
