/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { ServiceDTO } from "./ServiceDTO";
import { ServiceDTOFromJSON, ServiceDTOFromJSONTyped, ServiceDTOToJSON, ServiceDTOToJSONTyped } from "./ServiceDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface ServiceDTOListResponseWrapper
 */
export interface ServiceDTOListResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof ServiceDTOListResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof ServiceDTOListResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {Array<ServiceDTO>}
   * @memberof ServiceDTOListResponseWrapper
   */
  response?: Array<ServiceDTO> | null;
}

/**
 * Check if a given object implements the ServiceDTOListResponseWrapper interface.
 */
export function instanceOfServiceDTOListResponseWrapper(value: object): value is ServiceDTOListResponseWrapper {
  return true;
}

export function ServiceDTOListResponseWrapperFromJSON(json: any): ServiceDTOListResponseWrapper {
  return ServiceDTOListResponseWrapperFromJSONTyped(json, false);
}

export function ServiceDTOListResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDTOListResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : (json["response"] as Array<any>).map(ServiceDTOFromJSON),
  };
}

export function ServiceDTOListResponseWrapperToJSON(json: any): ServiceDTOListResponseWrapper {
  return ServiceDTOListResponseWrapperToJSONTyped(json, false);
}

export function ServiceDTOListResponseWrapperToJSONTyped(value?: ServiceDTOListResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: value["response"] == null ? undefined : (value["response"] as Array<any>).map(ServiceDTOToJSON),
  };
}
