/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { ServiceDTO } from "./ServiceDTO";
import { ServiceDTOFromJSON, ServiceDTOFromJSONTyped, ServiceDTOToJSON, ServiceDTOToJSONTyped } from "./ServiceDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface ServiceDTOResponseWrapper
 */
export interface ServiceDTOResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof ServiceDTOResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof ServiceDTOResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {ServiceDTO}
   * @memberof ServiceDTOResponseWrapper
   */
  response?: ServiceDTO;
}

/**
 * Check if a given object implements the ServiceDTOResponseWrapper interface.
 */
export function instanceOfServiceDTOResponseWrapper(value: object): value is ServiceDTOResponseWrapper {
  return true;
}

export function ServiceDTOResponseWrapperFromJSON(json: any): ServiceDTOResponseWrapper {
  return ServiceDTOResponseWrapperFromJSONTyped(json, false);
}

export function ServiceDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDTOResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : ServiceDTOFromJSON(json["response"]),
  };
}

export function ServiceDTOResponseWrapperToJSON(json: any): ServiceDTOResponseWrapper {
  return ServiceDTOResponseWrapperToJSONTyped(json, false);
}

export function ServiceDTOResponseWrapperToJSONTyped(value?: ServiceDTOResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: ServiceDTOToJSON(value["response"]),
  };
}
