/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ServiceBasicDTO
 */
export interface ServiceBasicDTO {
  /**
   *
   * @type {string}
   * @memberof ServiceBasicDTO
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof ServiceBasicDTO
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof ServiceBasicDTO
   */
  userId?: string | null;
  /**
   *
   * @type {Date}
   * @memberof ServiceBasicDTO
   */
  createdAt?: Date;
}

/**
 * Check if a given object implements the ServiceBasicDTO interface.
 */
export function instanceOfServiceBasicDTO(value: object): value is ServiceBasicDTO {
  return true;
}

export function ServiceBasicDTOFromJSON(json: any): ServiceBasicDTO {
  return ServiceBasicDTOFromJSONTyped(json, false);
}

export function ServiceBasicDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBasicDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    userId: json["userId"] == null ? undefined : json["userId"],
    createdAt: json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
  };
}

export function ServiceBasicDTOToJSON(json: any): ServiceBasicDTO {
  return ServiceBasicDTOToJSONTyped(json, false);
}

export function ServiceBasicDTOToJSONTyped(value?: ServiceBasicDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    userId: value["userId"],
    createdAt: value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
  };
}
