/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RequestAction } from "./RequestAction";
import { RequestActionFromJSON, RequestActionFromJSONTyped, RequestActionToJSON, RequestActionToJSONTyped } from "./RequestAction";

/**
 *
 * @export
 * @interface ServicePermissionOnUserUpdateDTOInner
 */
export interface ServicePermissionOnUserUpdateDTOInner {
  /**
   *
   * @type {string}
   * @memberof ServicePermissionOnUserUpdateDTOInner
   */
  permissionId?: string | null;
  /**
   *
   * @type {RequestAction}
   * @memberof ServicePermissionOnUserUpdateDTOInner
   */
  action?: RequestAction;
}

/**
 * Check if a given object implements the ServicePermissionOnUserUpdateDTOInner interface.
 */
export function instanceOfServicePermissionOnUserUpdateDTOInner(value: object): value is ServicePermissionOnUserUpdateDTOInner {
  return true;
}

export function ServicePermissionOnUserUpdateDTOInnerFromJSON(json: any): ServicePermissionOnUserUpdateDTOInner {
  return ServicePermissionOnUserUpdateDTOInnerFromJSONTyped(json, false);
}

export function ServicePermissionOnUserUpdateDTOInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicePermissionOnUserUpdateDTOInner {
  if (json == null) {
    return json;
  }
  return {
    permissionId: json["permissionId"] == null ? undefined : json["permissionId"],
    action: json["action"] == null ? undefined : RequestActionFromJSON(json["action"]),
  };
}

export function ServicePermissionOnUserUpdateDTOInnerToJSON(json: any): ServicePermissionOnUserUpdateDTOInner {
  return ServicePermissionOnUserUpdateDTOInnerToJSONTyped(json, false);
}

export function ServicePermissionOnUserUpdateDTOInnerToJSONTyped(
  value?: ServicePermissionOnUserUpdateDTOInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    permissionId: value["permissionId"],
    action: RequestActionToJSON(value["action"]),
  };
}
