/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { SessionDTO } from "./SessionDTO";
import { SessionDTOFromJSON, SessionDTOFromJSONTyped, SessionDTOToJSON, SessionDTOToJSONTyped } from "./SessionDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface SessionDTOListResponseWrapper
 */
export interface SessionDTOListResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof SessionDTOListResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof SessionDTOListResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {Array<SessionDTO>}
   * @memberof SessionDTOListResponseWrapper
   */
  response?: Array<SessionDTO> | null;
}

/**
 * Check if a given object implements the SessionDTOListResponseWrapper interface.
 */
export function instanceOfSessionDTOListResponseWrapper(value: object): value is SessionDTOListResponseWrapper {
  return true;
}

export function SessionDTOListResponseWrapperFromJSON(json: any): SessionDTOListResponseWrapper {
  return SessionDTOListResponseWrapperFromJSONTyped(json, false);
}

export function SessionDTOListResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDTOListResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : (json["response"] as Array<any>).map(SessionDTOFromJSON),
  };
}

export function SessionDTOListResponseWrapperToJSON(json: any): SessionDTOListResponseWrapper {
  return SessionDTOListResponseWrapperToJSONTyped(json, false);
}

export function SessionDTOListResponseWrapperToJSONTyped(value?: SessionDTOListResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: value["response"] == null ? undefined : (value["response"] as Array<any>).map(SessionDTOToJSON),
  };
}
