/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateNameDTO
 */
export interface UpdateNameDTO {
  /**
   *
   * @type {string}
   * @memberof UpdateNameDTO
   */
  name?: string | null;
}

/**
 * Check if a given object implements the UpdateNameDTO interface.
 */
export function instanceOfUpdateNameDTO(value: object): value is UpdateNameDTO {
  return true;
}

export function UpdateNameDTOFromJSON(json: any): UpdateNameDTO {
  return UpdateNameDTOFromJSONTyped(json, false);
}

export function UpdateNameDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNameDTO {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function UpdateNameDTOToJSON(json: any): UpdateNameDTO {
  return UpdateNameDTOToJSONTyped(json, false);
}

export function UpdateNameDTOToJSONTyped(value?: UpdateNameDTO | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
  };
}
