/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { UserDTO } from "./UserDTO";
import { UserDTOFromJSON, UserDTOFromJSONTyped, UserDTOToJSON, UserDTOToJSONTyped } from "./UserDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface UserDTOResponseWrapper
 */
export interface UserDTOResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof UserDTOResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof UserDTOResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {UserDTO}
   * @memberof UserDTOResponseWrapper
   */
  response?: UserDTO;
}

/**
 * Check if a given object implements the UserDTOResponseWrapper interface.
 */
export function instanceOfUserDTOResponseWrapper(value: object): value is UserDTOResponseWrapper {
  return true;
}

export function UserDTOResponseWrapperFromJSON(json: any): UserDTOResponseWrapper {
  return UserDTOResponseWrapperFromJSONTyped(json, false);
}

export function UserDTOResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTOResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : UserDTOFromJSON(json["response"]),
  };
}

export function UserDTOResponseWrapperToJSON(json: any): UserDTOResponseWrapper {
  return UserDTOResponseWrapperToJSONTyped(json, false);
}

export function UserDTOResponseWrapperToJSONTyped(value?: UserDTOResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: UserDTOToJSON(value["response"]),
  };
}
