/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WrResponseStatus } from "./WrResponseStatus";
import { WrResponseStatusFromJSON, WrResponseStatusFromJSONTyped, WrResponseStatusToJSON, WrResponseStatusToJSONTyped } from "./WrResponseStatus";
import type { UserDTO } from "./UserDTO";
import { UserDTOFromJSON, UserDTOFromJSONTyped, UserDTOToJSON, UserDTOToJSONTyped } from "./UserDTO";
import type { AuthFailureReasons } from "./AuthFailureReasons";
import {
  AuthFailureReasonsFromJSON,
  AuthFailureReasonsFromJSONTyped,
  AuthFailureReasonsToJSON,
  AuthFailureReasonsToJSONTyped,
} from "./AuthFailureReasons";

/**
 *
 * @export
 * @interface UserDTOListResponseWrapper
 */
export interface UserDTOListResponseWrapper {
  /**
   *
   * @type {WrResponseStatus}
   * @memberof UserDTOListResponseWrapper
   */
  status?: WrResponseStatus;
  /**
   *
   * @type {Array<AuthFailureReasons>}
   * @memberof UserDTOListResponseWrapper
   */
  authenticationFailureReasons?: Array<AuthFailureReasons> | null;
  /**
   *
   * @type {Array<UserDTO>}
   * @memberof UserDTOListResponseWrapper
   */
  response?: Array<UserDTO> | null;
}

/**
 * Check if a given object implements the UserDTOListResponseWrapper interface.
 */
export function instanceOfUserDTOListResponseWrapper(value: object): value is UserDTOListResponseWrapper {
  return true;
}

export function UserDTOListResponseWrapperFromJSON(json: any): UserDTOListResponseWrapper {
  return UserDTOListResponseWrapperFromJSONTyped(json, false);
}

export function UserDTOListResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTOListResponseWrapper {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"] == null ? undefined : WrResponseStatusFromJSON(json["status"]),
    authenticationFailureReasons:
      json["authenticationFailureReasons"] == null ? undefined : (json["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsFromJSON),
    response: json["response"] == null ? undefined : (json["response"] as Array<any>).map(UserDTOFromJSON),
  };
}

export function UserDTOListResponseWrapperToJSON(json: any): UserDTOListResponseWrapper {
  return UserDTOListResponseWrapperToJSONTyped(json, false);
}

export function UserDTOListResponseWrapperToJSONTyped(value?: UserDTOListResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    status: WrResponseStatusToJSON(value["status"]),
    authenticationFailureReasons:
      value["authenticationFailureReasons"] == null ? undefined : (value["authenticationFailureReasons"] as Array<any>).map(AuthFailureReasonsToJSON),
    response: value["response"] == null ? undefined : (value["response"] as Array<any>).map(UserDTOToJSON),
  };
}
