/* tslint:disable */
/* eslint-disable */
/**
 * nauth-asp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const WrResponseStatus = {
  InternalError: "InternalError",
  Ok: "Ok",
  Forbidden: "Forbidden",
  Unauthorized: "Unauthorized",
  NotFound: "NotFound",
  BadRequest: "BadRequest",
  Cooldown: "Cooldown",
  ServerDown: "ServerDown",
  EmailNotAvailable: "EmailNotAvailable",
  InvalidEmail: "InvalidEmail",
  InvalidPassword: "InvalidPassword",
  RequireEnabledUser: "RequireEnabledUser",
  InvalidApplyToken: "InvalidApplyToken",
} as const;
export type WrResponseStatus = (typeof WrResponseStatus)[keyof typeof WrResponseStatus];

export function instanceOfWrResponseStatus(value: any): boolean {
  for (const key in WrResponseStatus) {
    if (Object.prototype.hasOwnProperty.call(WrResponseStatus, key)) {
      if (WrResponseStatus[key as keyof typeof WrResponseStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function WrResponseStatusFromJSON(json: any): WrResponseStatus {
  return WrResponseStatusFromJSONTyped(json, false);
}

export function WrResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WrResponseStatus {
  return json as WrResponseStatus;
}

export function WrResponseStatusToJSON(value?: WrResponseStatus | null): any {
  return value as any;
}

export function WrResponseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WrResponseStatus {
  return value as WrResponseStatus;
}
